# Learn more → https://github.com/TryGhost/action-deploy-theme#getting-started
name: Deploy Theme

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: yarn.lock

      - run: yarn install --frozen-lockfile

      - run: yarn test:ci

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Deploy theme
        uses: TryGhost/action-deploy-theme@a0ee1147d15641db25681e54549c4db9a53c2629
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: Casper-Main
